name: Publish
on:
  schedule:
  - cron: '0 0 * * *'
  pull_request:
jobs:
  release:
    name: Packages
    if: github.repository == 'protobufjs/protobuf.js'
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
    with:
      ref: master
  - name: Install dependencies
    run: |
      npm -v
      npm install && (cd cli && npm install)
  - name: Build packages
    run: |
      VERSION=$(npx aspublish --version)
      if [[ "$VERSION" == "" ]]; then
        echo "Changes do not trigger a release"
      else
        echo "Building version: $VERSION"
        npm version "$VERSION" --no-git-tag-version
        npm run make
        npm test
        cd cli
        npm version "$VERSION" --no-git-tag-version
        cd ..
      fi
  - name: Publish packages
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    run: |
      if [ $(node -pe "require('./package.json').version") != "0.0.0" ]; then
        echo "npx aspublish, protobufjs@$VERSION"
      fi
      cd cli
      if [ $(node -pe "require('./package.json').version") != "0.0.0" ]; then
        echo "npm publish, protobufjs-cli@$VERSION"
      fi
