name: Publish
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  release:
    name: Packages
    if: github.repository == 'protobufjs/protobuf.js'
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
    with:
      ref: master
  - name: Install dependencies
    run: |
      npm -v
      npm ci && (cd cli && npm ci)
  - name: Build packages
    run: |
      VERSION=$(npx aspublish --version)
      if [[ "$VERSION" == "" ]]; then
        echo "Changes do not trigger a release"
      else
        echo "Building version: $VERSION"
        npm version "$VERSION" --no-git-tag-version
        npm run make
        npm test
      fi
  # - name: Publish packages
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #   run: |
  #     if [ $(node -pe "require('./package.json').version") != "0.0.0" ]; then
  #       npx aspublish
  #     fi
